### PR TITLE
Add address injection into transaction imports

### PR DESCRIPTION
**Pull request by adhurjaty**
Addresses issue #58

### CODE REVIEW

**Comment by tyronbrand** [comment]
I won't have time to fully review this today but I do have some comments so far...

1. I think that it would be better to move `AddressMap` out of `TransactionBase.cs` since this feature would ideally apply to both scripts and transactions. 
2. Ideally you can setup your desired import configuration and it would be applied to all scripts/transactions so you wouldn't have to add the changes into every request.

**Comment by adhurjaty** [comment]
> I won't have time to fully review this today but I do have some comments so far...
> 
> 1. I think that it would be better to move `AddressMap` out of `TransactionBase.cs` since this feature would ideally apply to both scripts and transactions.
> 2. Ideally you can setup your desired import configuration and it would be applied to all scripts/transactions so you wouldn't have to add the changes into every request.

For (1) then I think it would make sense to create some DTO for scripts to pass into the execute methods instead of passing in the script text and script params as separate parameters. We'd then create a converter similar to the TransactionConverter to create the object that gets passed to the protobuf library. This new DTO and TransactionBase would derive from some new abstract class that has `Script`, `Arguments` and `AddressMap` properties. This means changing the signature of the currently existing script execution methods and changing the documentation -- a breaking change

For (2): it's a good idea to have a kind of global or client-scoped address mapping for common imports (FungibleToken, FlowToken, etc), but I'd still like to allow the user to pass an address mapping into individual transaction executions. I can imagine scenarios where there might be name collisions that would require resetting the client-scoped address map if we don't also allow transaction-scoped address maps. This is how flow-js-testing works. Here's the [global mapping](https://github.com/onflow/flow-js-testing/blob/master/src/file.js) and where you can define [transaction-scoped address map](https://github.com/onflow/flow-js-testing/blob/f3d43cd41888c3dd413ea10027e470fe08084d83/src/interaction.js#L101).

If this sounds good to you, I'll update this PR with the changes

**Comment by tyronbrand** [comment]
Your proposed solution sounds good to me.

**Comment by adhurjaty** [comment]
Added the features suggested

**Pull request merged**
